feat: change in naming conventions for readability, major change in wakeword detection from the conventional call-response before a command is made to tracking phrases prior to the wakeword and thereafter.

diff --git a/bin/core-config b/bin/core-config
--- a/bin/core-config
+++ b/bin/core-config
@@ -1,247 +1,246 @@
 #!/usr/bin/env bash
 
 SOURCE="${BASH_SOURCE[0]}"
-cd -P "$( dirname "$SOURCE" )" || exit
-DIR="$( pwd )"
+cd -P "$(dirname "$SOURCE")" || exit
+DIR="$(pwd)"
 script=${0}
 script=${script##*/}
 
 function help() {
-    echo "${script}:  configuration manager"
-    echo "usage: ${script} [COMMAND] [params]"
-    echo
-    echo "COMMANDs:"
-    echo "  edit (system|user)                  edit and validate config file"
-    echo "  reload                              instruct services to reload config"
-    echo "  show (default|remote|system|user)   display the specified setting file"
-    echo "  set <var>                           set the variable (under USER)"
-    echo "  get [var]                           display a particular variable"
-    echo "                                      or all if no 'var' specified"
-    echo "Note: Use jq format for specifying <var>"
-    echo
-    echo "Examples:"
-    echo "  ${script} edit user"
-    echo "  sudo ${script} edit system"
-    echo "  ${script} show remote"
-    echo "  ${script} get"
-    echo "  ${script} get enclosure.platform"
-    echo "  ${script} set test.subvalue \"foo\" "
+	echo "${script}:  configuration manager"
+	echo "usage: ${script} [COMMAND] [params]"
+	echo
+	echo "COMMANDs:"
+	echo "  edit (system|user)                  edit and validate config file"
+	echo "  reload                              instruct services to reload config"
+	echo "  show (default|remote|system|user)   display the specified setting file"
+	echo "  set <var>                           set the variable (under USER)"
+	echo "  get [var]                           display a particular variable"
+	echo "                                      or all if no 'var' specified"
+	echo "Note: Use jq format for specifying <var>"
+	echo
+	echo "Examples:"
+	echo "  ${script} edit user"
+	echo "  sudo ${script} edit system"
+	echo "  ${script} show remote"
+	echo "  ${script} get"
+	echo "  ${script} get enclosure.platform"
+	echo "  ${script} set test.subvalue \"foo\" "
 
-    exit 1
+	exit 1
 }
 
 ################################################################
 # Setup stuff based on the environment
 
 VIEWER="nano --syntax=json --view"
-if [ -z "$EDITOR" ] ; then
-    if which sensible-editor > /dev/null ; then
-        EDITOR="sensible-editor"
-    else
-        EDITOR="nano --syntax=json --tempfile"
-    fi
+if [ -z "$EDITOR" ]; then
+	if which sensible-editor >/dev/null; then
+		EDITOR="sensible-editor"
+	else
+		EDITOR="nano --syntax=json --tempfile"
+	fi
 fi
 
-if [ -z "$TEMP" ] ; then
-    TEMP="/tmp"
+if [ -z "$TEMP" ]; then
+	TEMP="/tmp"
 fi
 
 function found_exe() {
-    hash "$1" 2>/dev/null
+	hash "$1" 2>/dev/null
 }
 
-if found_exe tput ; then
-    # shellcheck disable=SC2034
-    GREEN="$(tput setaf 2)"
-    # shellcheck disable=SC2034
-    BLUE="$(tput setaf 4)"
-    # shellcheck disable=SC2034
-    CYAN="$(tput setaf 6)"
-    # shellcheck disable=SC2034
-    YELLOW="$(tput setaf 3)"
-    # shellcheck disable=SC2034
-    RESET="$(tput sgr0)"
-    # shellcheck disable=SC2034
-    HIGHLIGHT=${YELLOW}
+if found_exe tput; then
+	# shellcheck disable=SC2034
+	GREEN="$(tput setaf 2)"
+	# shellcheck disable=SC2034
+	BLUE="$(tput setaf 4)"
+	# shellcheck disable=SC2034
+	CYAN="$(tput setaf 6)"
+	# shellcheck disable=SC2034
+	YELLOW="$(tput setaf 3)"
+	# shellcheck disable=SC2034
+	RESET="$(tput sgr0)"
+	# shellcheck disable=SC2034
+	HIGHLIGHT=${YELLOW}
 fi
 
 ################################################################
 # Utilities
 
 function validate_config_file() {
-    if [ ! -f "$1" ] ; then
-        # A missing config file is valid
-        return 0
-    fi
+	if [ ! -f "$1" ]; then
+		# A missing config file is valid
+		return 0
+	fi
 
-    echo -n "${BLUE}"
+	echo -n "${BLUE}"
 
-    # Remove any comments (lines starting with # or //) found in the file and
-    # Use jq to validate and output errors
-    sed 's/^\s*[#\/].*$//g' "$1" | sed '/^$/d' | jq -e "." > /dev/null
-    result=$?
+	# Remove any comments (lines starting with # or //) found in the file and
+	# Use jq to validate and output errors
+	sed 's/^\s*[#\/].*$//g' "$1" | sed '/^$/d' | jq -e "." >/dev/null
+	result=$?
 
-    echo -n "${RESET}"
+	echo -n "${RESET}"
 
-    #xxx echo "RESULT=$result for $1"
-    return $result
+	#xxx echo "RESULT=$result for $1"
+	return $result
 }
 
 _conf_file="${XDG_CONFIG_HOME:-$HOME/.config}/core/core.conf"
 function name_to_path() {
-    case ${1} in
-        "system")     _conf_file="/etc/core/core.conf" ;;
-        "user")       _conf_file=$(readlink -f "${XDG_CONFIG_HOME:-$HOME/.config}/core/core.conf") ;;
-        "default")    _conf_file="$DIR/../core/configuration/core.conf" ;;
-        "remote")     _conf_file="$HOME/.cache/mycroft/web_cache.json" ;;
+	case ${1} in
+	"system") _conf_file="/etc/core/core.conf" ;;
+	"user") _conf_file=$(readlink -f "${XDG_CONFIG_HOME:-$HOME/.config}/core/core.conf") ;;
+	"default") _conf_file="$DIR/../core/configuration/core.conf" ;;
+	"remote") _conf_file="$HOME/.cache/mycroft/web_cache.json" ;;
 
-        *)
-            echo "ERROR: Unknown name '${1}'."
-            echo "       Must be one of: default, remote, system, or user"
-            exit 1
-    esac
+	*)
+		echo "ERROR: Unknown name '${1}'."
+		echo "       Must be one of: default, remote, system, or user"
+		exit 1
+		;;
+	esac
 }
 
 ################################################################
 
 function edit_config() {
-    name_to_path "$1"
-    validate_config_file "$_conf_file"
-    rc=$?
-    if [ $rc -ne 0 ] ; then
-        echo "${YELLOW}WARNING: ${RESET}Configuration file did not pass validation before edits."
-        read -r -p "Review errors above and press ENTER to continue with editing."
-    fi
+	name_to_path "$1"
+	validate_config_file "$_conf_file"
+	rc=$?
+	if [ $rc -ne 0 ]; then
+		echo "${YELLOW}WARNING: ${RESET}Configuration file did not pass validation before edits."
+		read -r -p "Review errors above and press ENTER to continue with editing."
+	fi
 
-    if [ -f "${_conf_file}" ] ; then
-        cp "${_conf_file}" "${TEMP}/core.json"
-    else
-        echo "{" > "${TEMP}/core.json"
-        echo "}" >> "${TEMP}/core.json"
-    fi
+	if [ -f "${_conf_file}" ]; then
+		cp "${_conf_file}" "${TEMP}/core.json"
+	else
+		echo "{" >"${TEMP}/core.json"
+		echo "}" >>"${TEMP}/core.json"
+	fi
 
-    while true ; do
-        case $1 in
-        system | user)
-            # Allow user to edit
-            $EDITOR $TEMP/core.json
-            ;;
-        default | remote)
-            # View-only
-            echo "The default config shouldn't be changed, opening in View mode"
-            sleep 2
-            $VIEWER $TEMP/core.json
-            ;;
-        esac
+	while true; do
+		case $1 in
+		system | user)
+			# Allow user to edit
+			$EDITOR $TEMP/core.json
+			;;
+		default | remote)
+			# View-only
+			echo "The default config shouldn't be changed, opening in View mode"
+			sleep 2
+			$VIEWER $TEMP/core.json
+			;;
+		esac
 
-        cmp --quiet "${_conf_file}" "${TEMP}/core.json"
-        rc=$?
-        if [ $rc -eq 0 ] ; then
-            echo "Configuration unchanged."
-            break
-        fi
+		cmp --quiet "${_conf_file}" "${TEMP}/core.json"
+		rc=$?
+		if [ $rc -eq 0 ]; then
+			echo "Configuration unchanged."
+			break
+		fi
 
-        # file was changed, validate changes
-        if validate_config_file $TEMP/core.json > /dev/null ; then
-            key="S"
-        else
-            echo "${YELLOW}WARNING: ${RESET}Configuration file does not pass validation, see errors above."
-            echo "Press X to abandon changes, S to force save, any other key to edit again."
-            read -r -N1 -s key
-        fi
+		# file was changed, validate changes
+		if validate_config_file $TEMP/core.json >/dev/null; then
+			key="S"
+		else
+			echo "${YELLOW}WARNING: ${RESET}Configuration file does not pass validation, see errors above."
+			echo "Press X to abandon changes, S to force save, any other key to edit again."
+			read -r -N1 -s key
+		fi
 
-        case $key in
-        [Ss])
-            echo "Saving..."
-            mv $TEMP/core.json "$_conf_file"
-            signal_reload_config
-            break
-            ;;
-        [Xx])
-            # abandoning
-            break
-            ;;
-        esac
+		case $key in
+		[Ss])
+			echo "Saving..."
+			mv $TEMP/core.json "$_conf_file"
+			signal_reload_config
+			break
+			;;
+		[Xx])
+			# abandoning
+			break
+			;;
+		esac
 
-    done
+	done
 }
 
 function signal_reload_config() {
-    # Enter the venv
-    if [ -z "$CONDA_DEFAULT_ENV" ]
-    then
-        echo "conda is not activated, activating it now"
-        source $(conda info --base)/etc/profile.d/conda.sh
-        conda activate core 
-    fi
-    # source "$DIR/../venv-activate.sh" -q
+	# Enter the venv
+	if [ -z "$CONDA_DEFAULT_ENV" ]; then
+		echo "conda is not activated, activating it now"
+		source $(conda info --base)/etc/profile.d/conda.sh
+		conda activate core
+	fi
+	# source "$DIR/../venv-activate.sh" -q
 
-    # Post a messagebus notification to reload the config file
-    python -m core.messagebus.send "configuration.updated"  "{}" > /dev/null
+	# Post a messagebus notification to reload the config file
+	python -m source.messagebus.send "configuration.updated" "{}" >/dev/null
 }
 
 function show_config() {
-    name_to_path "$1"
+	name_to_path "$1"
 
-    # Use jq to display formatted nicely (after stripping out comments)
-    sed 's/^\s*[#\/].*$//g' "${_conf_file}" | sed '/^$/d' | jq "."
+	# Use jq to display formatted nicely (after stripping out comments)
+	sed 's/^\s*[#\/].*$//g' "${_conf_file}" | sed '/^$/d' | jq "."
 }
 
 function get_config() {
-    value=$1
-    if [[ ! $value =~ ^\..* ]] ; then
-        # Add the leading period if not included
-        value=".${value}"
-    fi
+	value=$1
+	if [[ ! $value =~ ^\..* ]]; then
+		# Add the leading period if not included
+		value=".${value}"
+	fi
 
-    # Load all the configuration(s)
-    # json_config=$( source "$DIR/../venv-activate.sh" -q && python -c "import json; from core.configuration import Configuration; print(json.dumps(Configuration.get()))" )
-    if [ -z "$CONDA_DEFAULT_ENV" ]
-    then
-        echo "conda is not activated, activating it now"
-        source $(conda info --base)/etc/profile.d/conda.sh
-        conda activate core 
-    fi
-    json_config=$(python -c "import json; from core.configuration import Configuration; print(json.dumps(Configuration.get()))" )
+	# Load all the configuration(s)
+	# json_config=$( source "$DIR/../venv-activate.sh" -q && python -c "import json; from core.configuration import Configuration; print(json.dumps(Configuration.get()))" )
+	if [ -z "$CONDA_DEFAULT_ENV" ]; then
+		echo "conda is not activated, activating it now"
+		source $(conda info --base)/etc/profile.d/conda.sh
+		conda activate core
+	fi
+	json_config=$(python -c "import json; from core.configuration import Configuration; print(json.dumps(Configuration.get()))")
 
-    # Read the given variable from the mix
-    echo "${json_config}" | jq -r "${value}"
+	# Read the given variable from the mix
+	echo "${json_config}" | jq -r "${value}"
 }
 
 function set_config() {
-    # Set all overrides under the user configuration
-    value=$1
-    if [[ ! $value =~ ^\..* ]] ; then
-        # Add the leading period if not included
-        value=".${value}"
-    fi
+	# Set all overrides under the user configuration
+	value=$1
+	if [[ ! $value =~ ^\..* ]]; then
+		# Add the leading period if not included
+		value=".${value}"
+	fi
 
-    if jq "${value} = \"$2\"" "$_conf_file" > "${TEMP}/~core.conf" ; then
-        # Successful update, replace the config file
-        mv "${TEMP}/~core.conf" "$_conf_file"
-        signal_reload_config
-    fi
+	if jq "${value} = \"$2\"" "$_conf_file" >"${TEMP}/~core.conf"; then
+		# Successful update, replace the config file
+		mv "${TEMP}/~core.conf" "$_conf_file"
+		signal_reload_config
+	fi
 }
 
 _opt=$1
 case ${_opt} in
-    "edit")
-        edit_config "$2"
-        ;;
-    "reload")
-        signal_reload_config
-        ;;
-    "show")
-        show_config "$2"
-        ;;
-    "get")
-        get_config "$2"
-        ;;
-    "set")
-        set_config "$2" "$3"
-        ;;
+"edit")
+	edit_config "$2"
+	;;
+"reload")
+	signal_reload_config
+	;;
+"show")
+	show_config "$2"
+	;;
+"get")
+	get_config "$2"
+	;;
+"set")
+	set_config "$2" "$3"
+	;;
 
-    *)
-        help
-        ;;
+*)
+	help
+	;;
 esac
